apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubee-frontend-deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubee-frontend-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubee-backend-deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubee-backend-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
