---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubee-cluster
  region: ap-southeast-2

nodeGroups:
  - name: kubee-nodegroup
    instanceType: t3.micro
    desiredCapacity: 2
