---
apiVersion: v1
kind: Service
metadata:
  name: kubee-frontend
  labels:
    name: kubee-frontend
    app: kubee-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: kubee-frontend-pod
    app: kubee-app
